// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrctnkqrdrgpqoxiulwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyY3Rua3FyZHJncHFveGl1bHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTkyMjMsImV4cCI6MjA3MzI5NTIyM30.-pnAuPTpWhz4l5U-0klo5MXFWJGHj-CWqXV1g6W-1x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
