// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smyeilqctdjppwrdajpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNteWVpbHFjdGRqcHB3cmRhanB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzI0NDEsImV4cCI6MjA3MjY0ODQ0MX0.OiY_co6KR8LyVXVS-nnIB3heXNTpj2N9qKWLei9VrYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});